services:
  frontend:
    image: my-image-name
    build: .
    container_name: e-commerce-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Ignore node_modules to prevent conflicts
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
