services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - e_commerce_network

  e_commerce_db:
    image: mysql:8
    container_name: e_commerce_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - e_commerce_network

  auth-service:
    build: ./apps/auth-service
    container_name: auth_service
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=e_commerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./apps/auth-service:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - e_commerce_db
    networks:
      - e_commerce_network

  product-service:
    build: ./apps/product-service
    container_name: product_service
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=e_commerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./apps/product-service:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - e_commerce_db
    networks:
      - e_commerce_network

  notification-service:
    build: ./apps/notification-service
    container_name: notification_service
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=e_commerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./apps/notification-service:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - e_commerce_db
    networks:
      - e_commerce_network

  order-service:
    build: ./apps/order-service
    container_name: order_service
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=e_commerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./apps/order-service:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - e_commerce_db
    networks:
      - e_commerce_network

  api-gateway:
    build: ./apps/gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=auth-service
      - PRODUCT_SERVICE_URL=product-service
      - NOTIFICATION_SERVICE_URL=notification-service
      - ORDER_SERVICE_URL=order-service
      - DB_HOST=e_commerce_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=e_commerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./apps/gateway:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - auth-service
      - product-service
      - notification-service
      - order-service
      - rabbitmq
      - e_commerce_db
    networks:
      - e_commerce_network

volumes:
  rabbitmq_data:
    driver: local
  mysql_data:
    driver: local

networks:
  e_commerce_network:
    driver: bridge
