version: "3.8"

services:
  auth-service:
    build: ./apps/auth-service
    container_name: auth_service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
    networks:
      - e_commerce_network

  product-service:
    build: ./apps/product-service
    container_name: product_service
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
    networks:
      - e_commerce_network

  notification-service:
    build: ./apps/notification-service
    container_name: notification_service
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
    networks:
      - e_commerce_network

  order-service:
    build: ./apps/order-service
    container_name: order_service
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
    networks:
      - e_commerce_network

  api-gateway:
    build: ./apps/api-gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=auth_service
      - PRODUCT_SERVICE_URL=product_service
      - NOTIFICATION_SERVICE_URL=notification_service
      - ORDER_SERVICE_URL=order_service
      - DB_HOST=e_commerce_db
    networks:
      - e_commerce_network

  e_commerce_db:
    image: mysql:8
    container_name: e_commerce_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e_commerce
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - e_commerce_network

volumes:
  mysql_data:
    driver: local

networks:
  e_commerce_network:
    driver: bridge
