services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management plugin
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - e_commerce_network

  auth-service:
    build: ./apps/auth-service
    container_name: auth_service
    environment:
      - NODE_ENV=development
      - DB_HOST=e_commerce_db
      - RABBITMQ_URL=amqp://guest:guest@e_commerce_backend_rabbitmq:5672
    volumes:
      - auth_service_data:/app/data
    command: npm run start:dev
    depends_on:
      - rabbitmq
    networks:
      - e_commerce_network

volumes:
  rabbitmq_data:
    driver: local
  auth_service_data:
    driver: local

networks:
  e_commerce_network:
    driver: bridge
