import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/providers/providers";
import Header from "@/components/header/Header";

const notoSansArabic = localFont({
  src: "./../fonts/Montserrat/Montserrat-Medium.ttf",
  // src: [
  //   {
  //     path: "./../fonts/Montserrat/Montserrat-Regular.ttf",
  //     weight: "400",
  //     style: "normal",
  //   },
  //   {
  //     path: "./../fonts/Montserrat/Montserrat-Medium.ttf",
  //     weight: "700",
  //     style: "normal",
  //   },
  //   {
  //     path: "./../fonts/Montserrat/Montserrat-Bold.ttf",
  //     weight: "900",
  //     style: "normal",
  //   },
  // ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansArabic.className} antialiased`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
