import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/providers/providers";

const notoSansArabic = localFont({
  src: "./../fonts/NotoSansArabic_Regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansArabic.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
